# This project config file describes your project. See looper docs for details.

pep_version: 2.0.0
sample_table: microtest_annotation.tutorial.csv # sheet listing all samples in the project
sample_modifiers:
  derive:
    attributes: [data_source]
    sources:
      microtest: "microtest/data/{filename}"
  append:
    pipeline_interfaces:
      - "${CODE}/open_pipelines/amplicon_simple.interface.yaml"

looper:
  output_dir: "$HOME/microtest"
