pep_version: 2.0.0
project_name: microtest
project_description: A collection of very small NGS testing data
  # sample_annotation: one-row-per-sample metadata
sample_table: microtest_annotation.csv
sample_modifiers:
  derive:
    attributes: [data_source]
    sources:
      microtest: "${CODE}/microtest/data/{filename}"
      bsf_samples: "${RAWDATA}{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam"
  imply:
    - if:
        organism: "human"
      then:
        genome: "hg19"
        transcriptome: "hg19_cdna"
        macs_genome_size: "hs"
    - if:
        organism: "mouse"
      then:
        genome: "mm10"
        transcriptome: "mm10_cdna"
        macs_genome_size: "mm"
    - if:
        protocol: "Amplicon"
      then:
        pipeline_interfaces: "${CODE}/open_pipelines/amplicon_simple.interface.yaml"
    - if:
        protocol: "ATAC-seq"
      then:
        pipeline_interfaces: "${CODE}/open_pipelines/atacseq.interface.yaml"

looper:
  output_dir: ${HOME}/microtest
